# Generated by Django 5.1.1 on 2024-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('permite_recorrencia', models.BooleanField(default=False)),
                ('quantidade_recorrencia', models.IntegerField()),
                ('intervalo_recorrencia', models.IntegerField()),
                ('status_recorrencia', models.CharField(max_length=20)),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('valor_pagamento', models.IntegerField()),
            ],
        ),
    ]
